### ISSUE TITLE
rrules and frules

### ISSUE THREAD

**Issue by cortner** [ACEsuit/Polynomials4ML.jl#2]

**Comment by cortner** [comment]
looks like this will be taken care of by #39

**Comment by CheukHinHoJerry** [comment]
Many frules are missing so we should probably keep this open until someone works on it.

**Comment by cortner** [comment]
@CheukHinHoJerry  -- can we discuss here the general interface we want to provide? At the moment it seems a bit all over the place. 

Here is my current suggestion - for example for the function `evaluate`  : 
```julia
function rrule(::typeof(evaluate), basis, X)
     # value ... 
     pb = D -> (NoTangent(), NoTangent(), _pb_evaluate(basis, D, X))
     return val, pb 
end

function _pb_evaluate(basis::TBASIS, D, X)
    # return the grad w.r.t. X 
end

function rrule(::typeof(_pb_evaluate), basis, D, X)
     pb = D2 -> (NoTangent(), NoTangent(), _pb_pb_evaluate(basis, D2, D, X)...)
     return val, pb
end

function _pb_pb_evaluate(basis, D2, D, X)
   # ... 
   # return grad_D, grad_X
end
```

**Comment by CheukHinHoJerry** [comment]
I have been thinking about it for a while too.  I think what you suggest would be great.

One that that is not clear to me is that how we should go with pullbacks which need to use `val` or `dval`. For example in the current general pullback interface of radial basis:

```julia
function ChainRulesCore.rrule(::typeof(evaluate), basis::ScalarPoly4MLBasis, R::AbstractVector{<: Real})
   A, dR = evaluate_ed(basis, R)
   ∂R = similar(R)
   function pb(∂A)
        @assert size(∂A) == (length(R), length(basis))
        for i = 1:length(R)
            ∂R[i] = dot(@view(∂A[i, :]), @view(dR[i, :]))
        end
        return NoTangent(), NoTangent(), ∂R
   end
   return A, pb
end
```

Should we also pass in `val` and `dval` in `_pb_evaluate`?

**Comment by cortner** [comment]
Ah yes - we actually had this in the documentation!! I'll transfer it here.

**Comment by cortner** [comment]
This is what we say in the docs: 
```julia
∂X = pb_evaluate(basis, ∂B, X, args..)
```
where `args...` can be anything. And I think that's a good idea and solves your problem (probably was intended exactly for that?). But I would give it the underscore to emphasize that this should only be used by people who know what they are doing?!
```julia
∂X = _pb_evaluate(basis, ∂B, X, args..)
```
For the time being, I would not focus too much on the in-place version
```julia
_pb_evaluate!(∂X, basis, ∂B, X, args..)
```
I think that can be a future optimisation.

**Comment by cortner** [comment]
There is only one potential problem I foresee: The *value*, say `A`, is now a temporary or cached array. It might be re-used even though it still lives in the closure that defines the pullback. This is potentially really dangerous.

There are of course workarounds for it but we need to be mindful of this and tread very carefully.

**Comment by CheukHinHoJerry** [comment]
yes - this is exactly the problem that I want to mentioned yesterday with the lux interface. It is also difficult to track down the problem because it goes through Zygote.

**Comment by cortner** [comment]
interesting. 

I have 2 ideas: 
(1) have a reference counter in the `CachedArray`
(2) keep references to all cached arrays in a secondary pool and provide a mechanism to traverse the model and return *all* cached arrays back to the primary pool after the model evaluation is done.

**Comment by cortner** [comment]
something to think about carefully.

**Comment by CheukHinHoJerry** [comment]
the wave function code would be a good practical example that we can take reference to? Maybe I try with just copying to see how much performance we loss.

**Comment by cortner** [comment]
... yes but maybe mull it over for a day or so?

**Comment by CheukHinHoJerry** [comment]
Yes I think so... this week I have quite a lot on my table so I won't actually do anything until next week...

**Comment by cortner** [comment]
I think I want to declare this as now restricted to just rrules and close it. If/once we start caring about frules and about the in-place interface we can re-open separate more specific issues.
