### ISSUE TITLE
Symmetrization layer

### ISSUE THREAD

**Issue by CheukHinHoJerry** [ACEsuit/Polynomials4ML.jl#42]
I am doing that for single species case, after confirming it works fine I will then do that for multi-specices case.

A minor issue is that currently RepLieGroups is using P4ML so there is a circular dependency issue. However in RepLieGroups/src we do not need P4ML and we should remove that from deps.

**Comment by cortner** [comment]
I agree. RepLieGroups only needs to be assured that the basis transforms as expected.

However, I'm not convinced that P4ML should depend on RepLieGroups. For now can we please work in a separate "drafting repo"? I will create that now.

**Comment by CheukHinHoJerry** [comment]
Just done a first draft on this and I will wait for the `2023MitacsDV ` to repo to set up before I push the code.

**Comment by cortner** [comment]
We should think about how we can do the synmetrisation layer for real SH. Probably not hard, probably can be reduced to specifying the CG for rSH which should be a trivial linear transformation.

**Comment by cortner** [comment]
@CheukHinHoJerry  -- I talked to @zhanglw0521 about creating another package called `EquivariantLux.jl` in which we make available utility functions to build equivariant models from RepLie and P4ML. We can also develop some example models in that package. It could be a sort of intermediate layer between RepLie, P4ML and ACE.

**Comment by zhanglw0521** [comment]
Sorry, I should have mentioned this earlier - so now we have an [elementary version](https://github.com/cortner/ACEluxham) in this regard, which might be served as a starting point.

**Comment by CheukHinHoJerry** [comment]
Ah yes - thanks for noticing this.

**Comment by CheukHinHoJerry** [comment]
I believe this is already implemented - I will close this now.

Ref https://github.com/ACEsuit/RepLieGroups.jl/pull/7#issue-1768116439
