### ISSUE TITLE
Precompilation

### ISSUE THREAD

**Issue by cortner** [ACEsuit/Polynomials4ML.jl#47]
It seems P4ML doesn't precompile when used from ACE1x. See also ACEsuit/ACE1pack.jl#130

We need to fix this urgently. 

CC @tjjarvinen  @CheukHinHoJerry

**Comment by tjjarvinen** [comment]
The short therm fix is adding `__precompile__(false)`. This has no effect on the actual working of the package, except that it does not try to precompile and thus there will be no failure to precompile. Note that when precompile fails the package works like without precompile.

On fixing the issue itself. My quess is that ObjectPools might have something to do with this. Other than that Julia documentation has section on this [topic](https://docs.julialang.org/en/v1/manual/modules/#Module-initialization-and-precompilation).

When debugging this you can use `Base.compilecache(Base.identify_package("modulename"))` to trigger precompile and see does it work.

**Comment by CheukHinHoJerry** [comment]
I will try to see where is the problem and fix that.

**Comment by cortner** [comment]
This was not an issue with P4ML but with ACE1x and RepLieGrps
