### ISSUE TITLE
CachedArrays for Linear layer

### ISSUE THREAD

**Issue by CheukHinHoJerry** [ACEsuit/Polynomials4ML.jl#56]
Current we do not make good use of CachedArray in LinearLayer. Should implement this and test it someday.

**Comment by CheukHinHoJerry** [comment]
I am thinking to implement this but I am uncertain whether the CachedArray should go into `st` or the layer itself. @cortner Would be great if you can advice.

**Comment by cortner** [comment]
Both. And depending on use case one or the other should be called. (I think!)
