### ISSUE TITLE
compatibility with hyperduals 

### ISSUE THREAD

**Issue by CheukHinHoJerry** [ACEsuit/Polynomials4ML.jl#60]
We should probably introduce a new `Union` type instead of doing something like:
```julia
_valtype(::GaussianBasis, T::Type{<: Real}) = T
_valtype(::GaussianBasis, T::Type{<: Hyper{<:Real}}) = T
```
every time.

Due to this there is an issue with rtrig + hyperduals that I did a quick fix so that Bernie can use it. I will probably create a PR later today together with the above issue.

**Comment by cortner** [comment]
how does this relate to #27

**Comment by CheukHinHoJerry** [comment]
I think not quite related to SINGLE/BATCH. This is just something to reduce code repetition.

**Comment by cortner** [comment]
FWIW this repetition doesn't bother me at all. It seems very minor, just like documenting what type of inputs we allow. Why is it a problem?

**Comment by CheukHinHoJerry** [comment]
hmm what you say sounds right. I fixed this issue for multiple basis and that's why I think this might be an issue. Now I look at it again it should be minor. Will close this issue now.
