### ISSUE TITLE
Some Naming Polls

### ISSUE THREAD

**Issue by cortner** [ACEsuit/Polynomials4ML.jl#85]
I'd like to poll the developers of this package about some naming issues: 

(1) Package name: do we keep `Polynomials4ML` or change to `ACEkernels` or something else? Or split off the ACE stuff into a separate package?  The context for this question is that some operations we provide are really polynomial bases while others are some very unique tensor operations. 

(2) For the polynomial basis interface the terminology is now fairly settled to 
```julia
evaluate!
evaluate_ed!
evaluate_ed2!
```
I think this is fine and suggest to keep it unless there are dissenting views. 

(3) For the tensors this is less clear I think. 

(3.1) Pullbacks Options: 
```julia
pb_evaluate!
pullback_evaluate! 
```

(3.2) Double-pullback
```julia
pb_pb_evaluate!
pullback2_evaluate! 
pullback_pullback_evaluate!
```

(3.3) Push-forward
```julia
pfwd_evaluate!
pushforward_evaluate! 
```

Thoughts? 

CC @CheukHinHoJerry @DexuanZhou @zhanglw0521

**Comment by CheukHinHoJerry** [comment]
(1) I think keeping Polynomials4ML is good. It would be easier to maintain if everything about kernels are in the same package?

(3) I like all the shorter ones.

**Comment by zhanglw0521** [comment]
Given that this is a poll I guess I'd just express my thoughts - 

(1) I think this package could even be used outside the ACE community so it might be a good idea not to make its name ACE-related?

(2) I actually don't have any preference on this.

(3) I am for the longer names, or else the abbr. `p` would sometimes mean pull and sometimes push...?

**Comment by cortner** [comment]
I think `p` would be ambiguous, but `pb` and `pfwd` are fairly clear. That said, there is a good argument for full names too. Hence I am asking for preferences :).

**Comment by cortner** [comment]
@DexuanZhou and @hjchen1984 - if you have a view I'd be interested in hearing it!!

**Comment by wcwitt** [comment]
At risk of speaking out of turn, I prefer the more verbose names because I can mostly understand them without having immersed myself in the repo, whereas things like 'pb_' are less immediately interpretable

**Comment by cortner** [comment]
@wcwitt  -- not at all, thank you for chiming in. I somewhat agree with you. My only concern is the rever-over-reverse, i.e. second pullback. 
```
pullback_pullback_evaluate!(...)
```
looks nasty. But maybe this will be used so rarely that I just shouldn't worry.

**Comment by DexuanZhou** [comment]
(1) I think keeping Polynomials4ML or splitting off the ACE-related operations into a separate package both works well for me. (3) I prefer shorter names: Pullbacks: pb_evaluate! Double-pullback: pb_pb_evaluate! Push-forward: pfwd_evaluate!.

**Comment by zhanglw0521** [comment]
> @wcwitt -- not at all, thank you for chiming in. I somewhat agree with you. My only concern is the rever-over-reverse, i.e. second pullback.
> 
> ```
> pullback_pullback_evaluate!(...)
> ```
> 
> looks nasty. But maybe this will be used so rarely that I just shouldn't worry.

For that maybe `pullback2` would work? When I see `pullback2` I will recall `..._ed2` and can then guess the meaning.

**Comment by cortner** [comment]
What about the following list of functions: 
```julia
evaluate!
evaluate_ed! 
evaluate_ed2! 
pullback! 
pushforward!
```
and for 2nd-order, for now experimentally, 
```julia
pullback2!
pushforward2!
```

**Comment by cortner** [comment]
thanks everybody for the comments...
